### ISSUE TITLE
Game crash when trying to view in mods screen in game

### ISSUE THREAD

**Issue by OrcLord1699** [NovaMachina/ExNihiloSequentia#76]
**Describe the bug**
Game crash when trying to view in mods screen in game.
Error: java.lang.ArrayIndexOutOfBoundsException: 0

**To Reproduce**
Steps to reproduce the behaviour:
1. Load game and click on mods (button at home screen)
2. click on Ex Nihilo: Sequentia (trying to get to config and see details)
3. game crashes

**Expected behavior**
to see the details of the mod and a possible config file

**Screenshots**
<img width="428" alt="errorpic1" src="https://user-images.githubusercontent.com/75975941/102325184-c2464800-3fd2-11eb-940c-ba3b4eab19f0.PNG">

<img width="751" alt="errorpic2" src="https://user-images.githubusercontent.com/75975941/102325317-edc93280-3fd2-11eb-8d55-42b0b6f5ba47.PNG">

**Version**
Minecraft Version: 1.16.4
Forge Version: 35.1.13
Ex Nihilo: Sequentia Version: 1.3.2.0

**Additional context**
---- Minecraft Crash Report ----
// There are four lights!

Time: 16/12/20 7:09 PM
Description: mouseClicked event handler

java.lang.ArrayIndexOutOfBoundsException: 0
	at com.sun.nio.zipfs.ZipPath.getResolvedPath(ZipPath.java:428) ~[zipfs.jar:1.8.0_271] {}
	at com.sun.nio.zipfs.ZipPath.checkAccess(ZipPath.java:767) ~[zipfs.jar:1.8.0_271] {}
	at com.sun.nio.zipfs.ZipFileSystemProvider.checkAccess(ZipFileSystemProvider.java:187) ~[zipfs.jar:1.8.0_271] {re:classloading,re:classloading,re:classloading,re:classloading}
	at java.nio.file.Files.exists(Files.java:2385) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.packs.ModFileResourcePack.func_195766_a(ModFileResourcePack.java:68) ~[forge:?] {re:classloading}
	at net.minecraft.resources.ResourcePack.func_195763_b(SourceFile:53) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraftforge.fml.client.gui.screen.ModListScreen.lambda$updateCache$12(ModListScreen.java:422) ~[forge:?] {re:classloading}
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.client.gui.screen.ModListScreen.updateCache(ModListScreen.java:413) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.client.gui.screen.ModListScreen.setSelected(ModListScreen.java:397) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.client.gui.widget.ModListWidget$ModEntry.func_231044_a_(ModListWidget.java:111) ~[forge:?] {re:classloading}
	at net.minecraft.client.gui.widget.list.AbstractList.func_231044_a_(AbstractList.java:309) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?] {re:classloading}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:999) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4-forge-35.1.13.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.13.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.sun.nio.zipfs.ZipPath.getResolvedPath(ZipPath.java:428) ~[zipfs.jar:1.8.0_271] {}
	at com.sun.nio.zipfs.ZipPath.checkAccess(ZipPath.java:767) ~[zipfs.jar:1.8.0_271] {}
	at com.sun.nio.zipfs.ZipFileSystemProvider.checkAccess(ZipFileSystemProvider.java:187) ~[zipfs.jar:1.8.0_271] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at java.nio.file.Files.exists(Files.java:2385) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.packs.ModFileResourcePack.func_195766_a(ModFileResourcePack.java:68) ~[forge:?] {re:classloading}
	at net.minecraft.resources.ResourcePack.func_195763_b(SourceFile:53) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraftforge.fml.client.gui.screen.ModListScreen.lambda$updateCache$12(ModListScreen.java:422) ~[forge:?] {re:classloading}
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.client.gui.screen.ModListScreen.updateCache(ModListScreen.java:413) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.client.gui.screen.ModListScreen.setSelected(ModListScreen.java:397) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.client.gui.widget.ModListWidget$ModEntry.func_231044_a_(ModListWidget.java:111) ~[forge:?] {re:classloading}
	at net.minecraft.client.gui.widget.list.AbstractList.func_231044_a_(AbstractList.java:309) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?] {re:classloading}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
-- Affected screen --
Details:
	Screen name: net.minecraftforge.fml.client.gui.screen.ModListScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:999) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4-forge-35.1.13.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.13.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1906621672 bytes (1818 MB) / 5100273664 bytes (4864 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.13.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.13
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.13-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.13-universal.jar                |Forge                         |forge                         |35.1.13             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		exnihilosequentia-1.16-1.3.2.0.jar                |Ex Nihilo: Sequentia          |exnihilosequentia             |1.16-1.3.2.0        |DONE      |NOSIGNATURE
	Crash Report UUID: 9edd8dc2-1862-4cbf-bcee-5ffbd1a10e66
	Launched Version: 1.16.4-forge-35.1.13
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2080 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.67, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (Australia)
	CPU: 8x Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz

**Comment by NovaMachina** [comment]
I'm not sure that there is anything I can do about this issue. I think this might be a Forge issue, however I will take a look at it.

**Comment by NovaMachina** [comment]
Found issue. Fixed in next version.
